# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MindWay.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(17)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_8 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_8.setToolTip("")
        self.toolButton_8.setStatusTip("")
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_5.addWidget(self.toolButton_8)
        self.toolButton_9 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_9.setMouseTracking(True)
        self.toolButton_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_9.setToolTip("")
        self.toolButton_9.setStatusTip("")
        self.toolButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_5.addWidget(self.toolButton_9, 0, QtCore.Qt.AlignBottom)
        self.toolButton_10 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_10.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_5.addWidget(self.toolButton_10, 0, QtCore.Qt.AlignBottom)
        self.toolButton_11 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_11.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_11.setToolTip("")
        self.toolButton_11.setStatusTip("")
        self.toolButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_5.addWidget(self.toolButton_11, 0, QtCore.Qt.AlignBottom)
        self.toolButton_12 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_12.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_12.setToolTip("")
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_5.addWidget(self.toolButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton_7 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_7.setStatusTip("")
        self.toolButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_3.addWidget(self.toolButton_7, 0, QtCore.Qt.AlignRight)
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setDragDropOverwriteMode(True)
        self.listView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView.setBatchSize(100)
        self.listView.setObjectName("listView")
        self.horizontalLayout_3.addWidget(self.listView)
        self.toolButton_1 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_1.setStatusTip("")
        self.toolButton_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_1.setObjectName("toolButton_1")
        self.horizontalLayout_3.addWidget(self.toolButton_1, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_6 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_6.setToolTip("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_4.addWidget(self.toolButton_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_4.addWidget(self.toolButton_5, 0, QtCore.Qt.AlignTop)
        self.toolButton_4 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_4.addWidget(self.toolButton_4, 0, QtCore.Qt.AlignTop)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_4.addWidget(self.toolButton_3, 0, QtCore.Qt.AlignTop)
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_4.addWidget(self.toolButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
#        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dockWidget_2.setAcceptDrops(True)
        self.dockWidget_2.setToolTip("")
        self.dockWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget_2.setAutoFillBackground(False)
        self.dockWidget_2.setFloating(True)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setEnabled(True)
        self.dockWidgetContents_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dockWidgetContents_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dockWidgetContents_2.setAcceptDrops(True)
        self.dockWidgetContents_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidgetContents_2.setAutoFillBackground(True)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.textEdit = QtWidgets.QTextEdit(self.dockWidgetContents_2)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 661, 241))
        self.textEdit.setMidLineWidth(0)
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setLineWrapColumnOrWidth(1)
        self.textEdit.setObjectName("textEdit")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
#        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.dockWidget_2.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_8.setText(_translate("MainWindow", "V"))
        self.toolButton_9.setText(_translate("MainWindow", "文件"))
        self.toolButton_10.setText(_translate("MainWindow", "加行"))
        self.toolButton_11.setText(_translate("MainWindow", "打开"))
        self.toolButton_12.setText(_translate("MainWindow", "计算"))
        self.toolButton_7.setText(_translate("MainWindow", "<"))
        self.toolButton_1.setText(_translate("MainWindow", ">"))
        self.toolButton_6.setText(_translate("MainWindow", "搜索"))
        self.toolButton_5.setText(_translate("MainWindow", "另显"))
        self.toolButton_4.setText(_translate("MainWindow", "删行"))
        self.toolButton_3.setText(_translate("MainWindow", "恢复"))
        self.toolButton_2.setText(_translate("MainWindow", "退出"))

